### ISSUE TITLE
How to deal with more groups？

### ISSUE THREAD

**Issue by celizi** [kutlugsahin/vue-smooth-dnd#145]
How to deal with more groups？
Unknown number of groups，inside the for loop
 `getChildPayload1 (index) {
      return this.items1[index]
 },`

**Comment by P4Thi0ut** [comment]
@celizi : a very quick and dirty fix in case you need it to work immediately (as I do haha) is to edit the dist/index.js and change
`Line 1, Column 21426 : e.getOptions().getChildPayload(n)`
to 
`e.getOptions().getChildPayload(n,e.element.id)`

this way the getChildPayload will be called with an additional parameter containing the id on the HTML element.

See : 
`<Container group-name="1" id="container-0" :get-child-payload="getChildPayload" ... >`

This allows some changes to get a variable number of columns!

For instance I declare something like
`columns : [ [ array of element ], [ array of element ], ... ]`

In the template I define my container as follow :
`<Container group-name="1" id="container-0" :get-child-payload="getChildPayload" @drop="onDrop(0, $event)">`

with the id containing information about the container position (up to you), the getChildPayload is now a single function, and the drop event sends the index of the collection instead of its property name.

And the draggable line is as follow:
`<Draggable v-for="item in columns[0]" :key="item.id">`

And my getChildPayload is as : (according to the ID that I specified on the HTML element)
`getChildPayload (index, origin) { return this.columns[origin.substr("container-".length)][index]; },`
I can return the corresponding collection from the `columns` array.

======== in order to keep the Vue reactivity properties ==========
Up to this point, your collections will be updated but the changes won't apply in render. Make the following changes to preserve the Vue tracking on your arrays : 

Change the applydrag function to work with references instead of array copies :

          applyDrag (collectionIndex, dragResult) {
                const { removedIndex, addedIndex, payload } = dragResult
                if (removedIndex === null && addedIndex === null) return

                let itemToAdd = payload

                if (removedIndex !== null) {
                    itemToAdd = this.columns[collectionIndex].splice(removedIndex, 1)[0]
                }

                if (addedIndex !== null) {
                    this.columns[collectionIndex].splice(addedIndex, 0, itemToAdd)
                }
            },


Finally, update the onDrop function code with something like 

          onDrop (collection, dropResult) {      
                this.applyDrag(collection, dropResult);      
            },

Voilà! You should be able to have unknown number of collection and do a v-for on containers from there 👍  

Regards!

**Comment by celizi** [comment]
I think I get it

Thanks so much!
