### ISSUE TITLE
Why does the drop event fire for each list

### ISSUE THREAD

**Issue by davestewart** [kutlugsahin/vue-smooth-dnd#16]
Lovely library!

I'm using the cards example, why does the card drop event fire once for EACH column?

Why not ONCE just for the dropped column?

**Comment by kutlugsahin** [comment]
Thanks!
Good point. I am planning to change this so that it will only be fired for source and target containers. This behavior is implemented before the drag-end function is added to provide a callback for side effects like changing background color when drag is ended. Now there is drag-end for this purpose and I will update it soon.
Cheers!

**Comment by davestewart** [comment]
> I am planning to change this so that it will only be fired for source and target containers

Would it not be better to fire only for the target container, and pass some kind of reference to the source?

```js
onDrop (event) {
   console.log(event.source, event.target)
}
```

**Comment by kutlugsahin** [comment]
I wouldn't agree with that, Containers can live in different components across the application and applying the drop result to source container from target container looks a bit weird. It should be components own logic.

**Comment by davestewart** [comment]
So I'm just writing some tests, and it seems I didn't understand how your cards move example worked how I thought it did.

So, even with the conditional, the `move` code fires twice, one event with the `removedIndex` and one event with the `addedIndex`:

```
event 1: listId: 'list-1, removedIndex: 3, payload: { ... }
event 2: listId: 'list-2, addedIndex: 5, payload: { ... }
```

So in the example code:

1. on drag the payload is created
2. on drop, two separate function calls:
    1. the source items array has the removedIndex removed
    2. the target items array has the payload added at the addedIndex

So, essentially two steps, rather than two indexes, and a straight swap:

```
function move (source, target, removedIndex, addedIndex) {
    target.splice(addedIndex, 0, source.splice(removedIndex, 1)[0])
}
```

Can you explain the rationale?

**Comment by davestewart** [comment]
Just re-read your initial comment; should I be using the `drag-end` function you mention?

**Comment by davestewart** [comment]
So, this works for me with a nested set of items in columns, as per your example.

No need for getChildPayload, it can call be done with indices and some basic splicing:

```html
<Container
  ...
  @drop="e => onItemDrop(listIndex, e)"
>
...
</Container>
```

```js
function makeDropHandler (handler) {
  let src = null
  let trg = null

  function reset () {
    src = null
    trg = null
  }

  return function (list, event) {
    if (event.removedIndex !== null) {
      src = { list, index: event.removedIndex }
    }
    if (event.addedIndex !== null) {
      trg = { list, index: event.addedIndex }
    }
    if (src && trg) {
      this[handler](src.list, src.index, trg.list, trg.index)
      reset()
    }
  }
}

export default {
  methods: {
    ...
    onItemDrop: makeDropHandler('onDropComplete'),
    onDropComplete (fromList, fromIndex, toList, toIndex) {
      console.log(fromList, fromIndex, toList, toIndex)
    },
  }
}
```
```
// two columns of 3 items
0 0 1 0
1 0 0 1
0 1 1 0
1 0 0 2
0 1 1 0
1 0 1 2
```

If I pass these arguments to Vuex, I can do something as simple as this:

```js
  moveItemByIndices (state, [fromList, fromIndex, toList, toIndex]) {
    fromList = state.lists[fromList].items
    toList = state.lists[toList].items
    toList.splice(toIndex, 0, fromList.splice(fromIndex, 1)[0])
  },
```

It would be cool to have a built in `onDropComplete` handler, so at the end of the operation we can take action once.

**Comment by davestewart** [comment]
Hey @kutlugsahin - I updated the comment above with some new, really flexible code.

Would be great to get some further thoughts from you.

**Comment by kutlugsahin** [comment]
Hey @davestewart. I will go though them definitely and get back to you. Hard to find free time these days.

**Comment by kutlugsahin** [comment]
@davestewart 

Thanks for sharing the codes and ideas !! I really appreciate it!

I know, for the cards example and may be many examples there will be an array of objects to populate the draggables inside the container and for these cases the payload will be one the object in the array right? And if you manage the source and target containers in the same component you would have both data array at one place. And in the drop event all you need seems to be the removed and added indexes so that you can rearrange arrays accordingly. For the cards scenario this works perfectly. 
Think of a scenario that you have two containers that lives in two different components with no connection to each other. And the draggables of these containers are populated with different types of object with different layout. With this API you can still make drag and drop between them. 
Its perfectly OK that you implemented your helper function to handle your specific case but generalizing this would be making assumptions about how people will use the library. 
I will try to make an example code for this scenario as soon as I find an available time.

Cheers!

**Comment by davestewart** [comment]
Hey @kutlugsahin

Thanks for looking at the code and taking the time to explain things from another perspective!

I have some free time this week, so I'll look to build a small example as you describe.

FYI, my cards example is online if you want to check it out:

![screenshot](https://github.com/davestewart/vue-trello-clone/raw/master/docs/screenshot.png)

- https://github.com/davestewart/vue-trello-clone

It took about a day and is lovely and smooth – all thanks in no small part to your plugin!

**Comment by davestewart** [comment]
@kutlugsahin - FYI, new project: https://davestewart.github.io/app-diary

**Comment by kutlugsahin** [comment]
@davestewart 
Looks sweet! Love to see it helped you :)
