### ISSUE TITLE
Many DropZone with same group-name fire all drop event

### ISSUE THREAD

**Issue by sylfel** [kutlugsahin/vue-smooth-dnd#17]
Hi

I want to propose some "thing" and drop them in some container.
I reused a sandbox to try : https://codesandbox.io/s/ll1yrnq8w9

Expected : show [1 , xxx] or [ 2, xxx] depend on which container element are drop
Happens : always [2, xxx] , and console log both container drop event

**Comment by kutlugsahin** [comment]
Hi @sylfel 
Yes the drop function is called by every relavant container. (see [docs](https://github.com/kutlugsahin/vue-smooth-dnd#drop)) This is a behaviour that I will change since I added drag-end. So to see weather the drop is inside a container you need to check the addedIndex of dropResult parameter.

updated codesandbox:  [https://codesandbox.io/s/jzpw9ky2v3](https://codesandbox.io/s/jzpw9ky2v3)
