### ISSUE TITLE
Transform CSS property positions ghost element improperly

### ISSUE THREAD

**Issue by zerosym** [kutlugsahin/vue-smooth-dnd#31]
If there is a transform property on a containing element of the draggable items the ghost element will be shifted improperly, even if the transform doesn't actually move the element; e.g. translateX(0).  

Demo:
https://codesandbox.io/s/6y0nl531or

I'm not sure if this is something you'd want to handle in the codebase or if it's expected for the user to just negate the offset by styling the ghost element with an opposite transform, but it took me a bit to figure out what was going on with my use case -- dragging copy elements out of a Vuetify side drawer positioned to the right of the screen.

**Comment by kutlugsahin** [comment]
Hey @zerosym thanks for submitting the issue. After investigating I found the problem here which is that the ghost element is positioned as fixed when being dragged. The fixed elements inside the transformed elements are positioned relative to the transformed parent elements instead of window, which I did not anticipated before. I need to update dragging by using transforms instead of updating left and top of fixed element. I will fix that in the upcoming releases.
Cheers!

**Comment by TitanFighter** [comment]
This bug is introduced in v0.1.7

**Comment by kutlugsahin** [comment]
Hey @zerosym @TitanFighter I addressed this issue on v 0.2.6.
To fix the issue I have added the 'get-ghost-parent' property to container. In your case you need to set this value and return a non transformed element (such as document.body) that the ghost to be added in. Ghost will still be added as fixed and all the calculations will suppose to work correct. The only drawback of the workaround is that ghost will no longer be a child of container and any css rules according to that will not be applied to the ghost element. But this can be fixed easily with a css rule targeting the draggable element itself. Hope this helps and sorry for the delay.
Cheers!
