### ISSUE TITLE
`should-accept-drop` appears to fires more times than expected

### ISSUE THREAD

**Issue by davestewart** [kutlugsahin/vue-smooth-dnd#35]
I've been building a "lifecycle" demo to fully understand how things work in Smooth DnD. (I'll submit this as a PR when done)

If I start with 3 columns of draggables, then drag item 1 from column 1 to column 3:

![image](https://user-images.githubusercontent.com/132681/45415730-281a2b80-b676-11e8-9e9c-4c35fd9add14.png)

I get the following lifecycle events:

```
--> MOUSEDOWN + DRAG

    get-child-payload

3 x should-accept-drop

    should-accept-drop
    drag-start
    should-accept-drop
    drag-start
    should-accept-drop
    drag-start

    drag-enter

--> MOUSE MOVE

    drag-leave
    drag-enter
    drag-leave
    drag-enter

--> MOUSEUP

    should-animate-drop
    
    should-accept-drop
    drag-end
    should-accept-drop
    drag-end
    should-accept-drop
    drag-end
    
3 x drop
```

The docs for `should-accept-drop`state it is: "the function to be called by all containers before drag starts to determine the containers to which the drop is possible".

Therefore, I don't understand why there appear to be two very similar executions of `should-accept-drop` at the start of the drag. The wording above suggests it should be the second set, though the first set seems more obvious:

- the 3 x `should-accept-drop`s before **all** `drag-start`s
- the extra `should-accept-drop`s before **each of** the `drag-start`s

Then, there is this additional set at the end of the drag:

- the extra `should-accept-drop`s before **each of** the `drag-end`s

I have the latest master, and have installed all the latest dependencies.

I've forked the repo and the demo is here:

- https://github.com/davestewart/vue-smooth-dnd/blob/feature/events-demo/src/demo/pages/events.vue

Is this expected?

Thanks!

**Comment by kutlugsahin** [comment]
Hey Dave,

The life cycle demo idea sounds great! Thanks for the all the effort you made, really appreciate it! 
For the question: Yes should-accept-drop is called several times during the drag and drop process just like you said. For instance, before the drag-end is it called to get the value of the 'willAcceptDrop' parameter to pass to drag-end function. So I agree that it looks a bit weird to be called several times but it should not cause any bugs since should-accept-drop function is just has to be a pure function that has no side effects. Or may be I have to call it once and cache it. 

PS: Its summer season so I can't spent much time to reply issues or maintenance these days. Probably I will start to go over them starting from next month. Sorry for that.

**Comment by davestewart** [comment]
> Thanks for the all the effort you made, really appreciate it!

Hey, no worries! It's a great library, I really enjoy the final result; everything looks and feels so great, so I am invested in understanding it as well as I can.

I know I've created a lot of tickets recently, I'd actually like to be able to contribute to the core at some point, but I recognise there are of course ramifications for the dependent libraries.

I will make 2 PRs once I nail this:

- the lifecycle demo itself
- a docs update (to the Vue version of the lib only; you may want to disseminate to the other versions)

One other thing I could do if you like, and that is rewrite the Vue Demo to use Vue Router; this way the URL would update as you change demos, making it easier to share links and develop in general, as you always stay on the same demo.

Let me know if that's something you're interested in.

:D

**Comment by davestewart** [comment]
By the way, how does the library know WHICH of the `should-accept-drop` calls to recognise?

That is, I could return a different result from each, but it seems that one of them has to win out.

For example, what happens if I return true from the first, false from the second, and skipped the third?

**Comment by zerosym** [comment]
Each should-accept-drop corresponds to, in your example, a given column of draggables.  It's designed so you can return a different value from each, because each column might have different criteria for rejecting potential drops.  

Take the Trello example for instance, and imagine that you cannot have duplicate items for a given card.  That would mean when you drag an item each one of the cards (columns) should fire their own should-accept-drop and return potentially a different value depending on whether or not the item is already present for them.

So going back to your hypotethical...if you return true from first, false from second and skipped the third you would be able to drop your dragged item on the first and third column (assuming by skip you mean you don't supply a should-accept-drop function).

**Comment by kutlugsahin** [comment]
Great work! Closing the issue
