### ISSUE TITLE
How to use this?can you make more useful demos?

### ISSUE THREAD

**Issue by 3-hours** [kutlugsahin/vue-smooth-dnd#47]

**Comment by davestewart** [comment]
Have you not seen the demos folder?

- https://github.com/kutlugsahin/vue-smooth-dnd/tree/master/demo/pages

You can run these locally and play with them, or view online:

- https://kutlugsahin.github.io/vue-smooth-dnd

15 demos to play with is great.

**Comment by Sell24** [comment]
First let me thank you for sharing this. It really is a great package.

From my perspective, I think what he means is that it is a bit difficult to figure out what to do to create a simple DnD (for me, between two columns) from the demo code. It took me a while to decipher your examples to understand what the bare minimum was to get it to work due to the complexity of them and lack of comments within the code. The code under Usage in the read.me was missing the get_child_payload() so that coupled with looking at the utils file, I finally figured it out.

While I understand the need to highlight all the features and you're obviously quite skilled in your coding, but maybe a really dumbed down version with comments for us newbies would be helpful. :)

Again though, thanks for taking the time to provide this. Really nice job. 👍

**Comment by kutlugsahin** [comment]
Thanks for your comment. Happy to hear that you liked the package. There are two functions used in all demo files namely applyDrag and generateItems. I moved them and imported from a utility module not to rewrite them for all demo pages. I think they are pretty easy to track. You wont probably need generateItems in your apps since it just produces a random dummy array of objects. You may want to use to applyDrag function in same cases. But it's up to you how to manipulate you component state. Anyway if I find more time in the future I may improve demo app even possible to migrate them to codesandbox.io to make them easy to play with.
Cheers!
