### ISSUE TITLE
Nice Library, but how would I .....

### ISSUE THREAD

**Issue by jamesladd** [kutlugsahin/vue-smooth-dnd#7]
Hi Vue-smooth-dnd,

Very nice library you have created and some really good examples and documentation.

For my needs I'm looking at the Copy Draggable example and your API doco.
What I can't work out is how to control the 'dropzone' so that it is obvious to the 'dragger' that the 'dropzone' is a valid target. I can see from the Copy example that the target container sorts items to let me know the dragged item can be dropped. However, I'm actually just wanting to have the container change color or show a boarder. 

Again, awesome job on this lib.

How could I do this?

- James.

**Comment by etune** [comment]
@jamesladd I think I might have the same question. Take Trello for example. They add a dark background to the area where you can drop your draggable item...

![image](https://user-images.githubusercontent.com/2109780/40005657-83494140-5766-11e8-8cf5-230f85b60f5d.png)

Is that the functionality you are looking for as well? I think that's a nice feature.

**Comment by kutlugsahin** [comment]
Hi @jamesladd,
Thanks for your comments. Currently there is no callback fired from '' droppable" containers when a drag is started. But I think you can handle this in the drag-start event even it is fired only from the source container since you already know the possible target containers. Another possible way might be using the should-accept-drop function, it is called for every container after a drag is started, so that you can return the value as well as update the UI accordingly. But I think I will add this callback function to the api in future releases.

**Comment by kutlugsahin** [comment]
It is not documented yet but you can set the behavior of container to 'drop-zone' in order to prevent a container reordering its items when a drag is on it. So it will behave like just a drop zone not a sortable container.
