### ISSUE TITLE
TypeError: Illegal invocation while running tests with jest

### ISSUE THREAD

**Issue by freezer278** [kutlugsahin/vue-smooth-dnd#90]
While i run tests of files which use `import {Draggable, Container} from 'vue-smooth-dnd'`
i get the following output: 

```
TypeError: Illegal invocation

      at Node.get [as childNodes] (node_modules/jsdom/lib/jsdom/living/generated/Node.js:423:13)
      at Node.get (node_modules/smooth-dnd/dist/index.js:530:46)
      at node_modules/smooth-dnd/dist/index.js:528:57
      at Object.<anonymous> (node_modules/smooth-dnd/dist/index.js:534:14)
      at Object.<anonymous> (node_modules/smooth-dnd/dist/index.js:540:12)
      at n (node_modules/smooth-dnd/dist/index.js:10:25)
      at Object.<anonymous> (node_modules/smooth-dnd/dist/index.js:544:66)
      at Object.<anonymous> (node_modules/smooth-dnd/dist/index.js:752:12)
      at n (node_modules/smooth-dnd/dist/index.js:10:25)
      at Object.<anonymous> (node_modules/smooth-dnd/dist/index.js:757:23)
```

**Comment by freezer278** [comment]
solution can be found in: https://github.com/kutlugsahin/smooth-dnd/issues/36

**Comment by amendx** [comment]
For those (like me) that #36 didn't work, and also #52, I had to spend a few hours on it just to figure it out. 

Inside the `smooth-dnd` lib, there's a `polyfill.ts` that does, baiscally:
```js
// Overwrites native 'firstElementChild' prototype.
// Adds Document & DocumentFragment support for IE9 & Safari.
// Returns array instead of HTMLCollection.
(function(constructor) {
    if (constructor &&
        constructor.prototype &&
        constructor.prototype.firstElementChild == null) {
        Object.defineProperty(constructor.prototype, 'firstElementChild', {
            get: function() {
                var node, nodes = this.childNodes, i = 0;
                while (node = nodes[i++]) {
                    if (node.nodeType === 1) {
                        return node;
                    }
                }
                return null;
            }
        });
    }
})(Node || Element);
```
And that polyfill just aplly up to IE9 and Safari 8, also Chrome versions up to 29. Since we're on v.289 of chrome and others, that's not even usefull. In my (updated) package, I just removed this function and every Jest test works fine. 

I took the time to wrap everything up to my own way, removing the `smooth-dnd` dependency and making everything to .js. 

If you're still struggling with that issue, come take a look at my solution at [vue-dndrop](https://github.com/amendx/vue-dnd). 

If that, somehow helps you, let me know. 🐈
